### GET ALL
GET http://localhost:3003/api/blogs

### LOGIN 1
# @name login1
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "jari",
  "password": "salasana"
}

### LOGIN 2
# @name login2
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "sanna",
  "password": "kristiina"
}

### POST 1
# @name create1
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer {{login1.response.body.token}}

{
  "title": "Maailmanmatkaaja",
  "author": "Jari Ahonen",
  "url": "http://maailmanmatkaaja.com/esittely",
  "likes": 12
}

### GET 1
GET http://localhost:3003/api/blogs/{{create1.response.body.id}}

### DELETE 1
DELETE http://localhost:3003/api/blogs/{{create1.response.body.id}}
Authorization: Bearer {{login1.response.body.token}}

### POST 2
# @name create2
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer {{login2.response.body.token}}

{
  "title": "Syvä kauneus",
  "author": "Sanna Ahonen",
  "url": "http://syvavesi.fi/alussa"
}

### GET 2
GET http://localhost:3003/api/blogs/{{create2.response.body.id}}

### DELETE 2
DELETE http://localhost:3003/api/blogs/{{create2.response.body.id}}
Authorization: Bearer {{login2.response.body.token}}