### GET all

GET http://localhost:3001/api/persons/ HTTP/1.1

### GET one

GET http://localhost:3001/api/persons/68da95b6141dac366453848c HTTP/1.1

### GET info page

GET http://localhost:3001/info HTTP/1.1