### GET ALL
GET http://localhost:3003/api/blogs

### LOGIN 1
# @name login1
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "test username 1",
  "password": "password1"
}

### LOGIN 2
# @name login2
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "test username 2",
  "password": "password2"
}

### POST 1
# @name create1
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer {{login1.response.body.token}}

{
  "title": "Title 1",
  "author": "Author 1",
  "url": "http://example.com/blog1",
  "likes": 12
}

### GET 1
GET http://localhost:3003/api/blogs/{{create1.response.body.id}}

### DELETE 1
DELETE http://localhost:3003/api/blogs/{{create1.response.body.id}}

### POST 2
# @name create2
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer {{login2.response.body.token}}

{
  "title": "Title 2",
  "author": "Author 2",
  "url": "http://example.com/blog2"
}

### GET 2
GET http://localhost:3003/api/blogs/{{create2.response.body.id}}

### DELETE 2
DELETE http://localhost:3003/api/blogs/{{create2.response.body.id}}